numero1 = int(input('Digite o primeiro numero: '))
numero2 = int(input('Digite o segundo numero: '))
print('A soma é:', numero1 + numero2)
print('A subtração é:', numero1 - numero2)
print('A multiplicação é:', numero1 * numero2)
print('A divisão é:', numero1 / numero2)
